### ISSUE TITLE
Share example code for the computation of key statistics from SICE data sets

### ISSUE THREAD

**Issue by AdrienWehrle** [GEUS-SICE/SICE#35]
A script ready to use on the different SICE data sets showing an example of computation of key statistics such as the area-averaged albedo or the daily bare ice area through time should be made available. The aim being to facilitate the life of future users who will likely want a quick access to those variables, potentially on their own areas of interest.

**Comment by BaptisteVandecrux** [comment]
I don't think this is needed in the SICE main repo, which should be only processing script.
We can add post-processing scripts to a different repo like SICE-tools.

**Comment by AdrienWehrle** [comment]
> I don't think this is needed in the SICE main repo, which should be only processing script. We can add post-processing scripts to a different repo like SICE-tools.

I think I agree! Then we should add a link to this repo (probably a new one, different from SICE-tools that quite a lot of different things) in the README!

**Comment by AdrienWehrle** [comment]
I created a basis in https://github.com/GEUS-SICE/SICE-toolbox and will continue developing it!
