### ISSUE TITLE
 Suggestion: Raster with pixel original scene name

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-SICE/SICE#4]
Makes it possible to track date and time of acquisition for each pixel.

Should be added around here:
https://github.com/GEUS-SICE/SICE/blob/baf2244c630b5e49d5f17f2aab2925f25e734b93/dm.grass.sh#L73-L89

**Comment by mankoff** [comment]
The LUT is written out as a PNG. If the SZA_list or arr is also written out, then this feature is complete. For a pixel in a scene, check the LUT PNG to find the line #. look up that line # in the new SZA_list file to find what scene went into that pixel.
