### ISSUE TITLE
Grass GIS running problems

### ISSUE THREAD

**Issue by Geek-007** [GEUS-SICE/SICE#45]
Why do I get the following error when I run` grass -c mask.tif out`?

Starting GRASS ...
The LOCATION "SICE-2.3.1" does not exist. Please create it first

**Comment by AdrienWehrle** [comment]
Hi! `mask.tif` is only a temporary file so I would need more info to answer your question: how did you run SICE? Through [S3_wrapper.sh](https://github.com/GEUS-SICE/SICE/blob/master/S3_wrapper.sh)? If yes, the default one? Could you please your OS and GRASS specs and versions? Thank you!

**Comment by Geek-007** [comment]
GRASS GIS 6.4.4  ； Linux ecs-huanjingjiance 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


I ran it step by step, and the following prompt appeared when I ran S3_proc.sh
![image](https://user-images.githubusercontent.com/25733662/155080958-463d0d95-456b-44af-a9c9-b54acd414d73.png)

**Comment by AdrienWehrle** [comment]
What arguments did you pass to S3_proc.sh? Could you share your command? 
Here is an example: 
https://github.com/GEUS-SICE/SICE/blob/9aff0c52a5b5921df1bc7c5fb4b2473e68e43f27/S3_wrapper.sh#L74

**Comment by Geek-007** [comment]
![image](https://user-images.githubusercontent.com/25733662/155084496-011fd136-479f-484e-8b62-9f367c0dd35c.png)


![image](https://user-images.githubusercontent.com/25733662/155085602-74206c89-63b8-418f-8c94-35be4e239938.png)

This step works fine, but the message is prompted from the appearance of grass. 

![image](https://user-images.githubusercontent.com/25733662/155085992-68bc0dec-7c3a-4e3e-ba62-a6371964207e.png)

`grass -c ./mask.tif ${dest}/G_align --exec ./G_align.sh ${dest} ./mask.tif ${resize}`  .This command did not run successfully,Does this have anything to do with the grass version?

**Comment by AdrienWehrle** [comment]
> grass -c ./mask.tif ${dest}/G_align --exec ./G_align.sh ${dest} ./mask.tif ${resize} .This command did not run successfully,Does this have anything to do with the grass version?

I think this comes from an issue encountered when running GRASS for the first time without GUI in versions older than v7.0 (see e.g. [this thread](https://trac.osgeo.org/grass/ticket/2683)). SICE was developed on 7.4.0, could you upgrade GRASS to at least v7.0?

**Comment by Geek-007** [comment]
Ok, thank you. I'll try to upgrade grass

**Comment by Geek-007** [comment]
Hi, thanks for your help, after upgrading GRASS solved my problem.
Now I have a new question.
When I customize my study area to use the tool, I get the following error that the input map projection information cannot be converted to GRASS format. How do I make [mask.tif](https://github.com/GEUS-SICE/SICE/blob/master/masks/Svalbard_300m.tif) files？
![image](https://user-images.githubusercontent.com/25733662/155246024-6d5be718-e2c5-475e-b9d2-456426382b1a.png)

**Comment by AdrienWehrle** [comment]
Hi! 
How do you pass your study area? With a mask in a tiff file, a polygon, a JSON file?

**Comment by Geek-007** [comment]
Can we use the method in this webpage? [https://www.esa-landcover-cci.org/?q=node/197](https://www.esa-landcover-cci.org/?q=node/197)

**Comment by AdrienWehrle** [comment]
> Can we use the method in this webpage? https://www.esa-landcover-cci.org/?q=node/197

For what purpose? My question was more about how do you pass it into the SICE toolchain? As a geotiff then I suppose?

**Comment by Geek-007** [comment]
We applied the SICE  to a certain region in Asia, but found that the mask.tif file was required during the operation. We saw this paragraph in the [README](https://github.com/GEUS-SICE/SICE#regional-masks) that taught you how to make a mask.tif file. As prompted I downloaded the C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc file through the [C3S Climate Data Store (CDS)](https://cds.climate.copernicus.eu/cdsapp#!/dataset/satellite-land-cover?tab=form) website. Use the following commands to make a mask.tif file for our study area, then follow the README to run the SICE toolchain step by step.
`gdalwarp -of Gtiff -co COMPRESS=LZW -co TILED=YES -ot Byte -te 39 115 54 135 -tr 0.002777777777778 0.002777777777778 -t_srs EPSG:3413 NETCDF:C3S-LC-L4-LCCS-Map-300m-P1Y-2020-v2.1.1.nc:lccs_class nec.tif`
But we don't seem to be running smoothly, so can you give us some ideas? tks.

**Comment by AdrienWehrle** [comment]
The mask file needs resampling to match the Sentinel-3 resolution specified by the user. This is happening before [dm.sh](https://github.com/GEUS-SICE/SICE/blob/master/dm.sh) (which is the last step before sice.py is applied). This might be linked to your error but I would need more info to help you efficiently.

Therefore, for me to better understand what is not working on your end, could you please 

- run [S3_wrapper.sh](https://github.com/GEUS-SICE/SICE/blob/master/S3_wrapper.sh) with your inputs and share the entire log?
- share the mask you are currently using?
