### ISSUE TITLE
Need to provide flag for cloud instead of removing cloudy pixels

### ISSUE THREAD

**Issue by BaptisteVandecrux** [GEUS-SICE/SICE#5]
Because:
1) cloud detection still very unstable:
![billede](https://user-images.githubusercontent.com/35140661/98468630-a5507500-21db-11eb-9068-fc37caf836b8.png)

2) bands such as "diagnostic_retrieval" are useful even in presence of clouds. 

I guess it should be done about here:
https://github.com/GEUS-SICE/SICE/blob/baf2244c630b5e49d5f17f2aab2925f25e734b93/dm.grass.sh#L64-L68

Or did I miss the motivation behind removing cloudy pixels?

**Comment by AdrienWehrle** [comment]
I agree and will work on it. There could be two cloud masks: the original one and the one with cloud buffering. I think the motivation behind it was to save space and only keep the results we needed in the first place.

**Comment by BaptisteVandecrux** [comment]
I don't think the buffer is a bad idea if the cloud mask is good. There are a lot of undesired pixels around clouds (shaddows, reflected sunlight...): 
![billede](https://user-images.githubusercontent.com/35140661/98922953-5a807700-24d3-11eb-8c2d-0d65cdbf3d8d.png)

A cloud mask with two types of flags (cloud or cloud buffer) would be optimal.
